name: Use HCP Vault Secrets in GitHub Actions

on:
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install HCP CLI (Fix GPG Key Issue)
        run: |
          sudo mkdir -p /usr/share/keyrings
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          echo "deb [trusted=yes] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update --allow-insecure-repositories && sudo apt install -y --allow-unauthenticated hcp-cli
      
      - name: Authenticate with HCP Vault Secrets and Retrieve Secrets
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
        run: |
          echo "$HCP_CLIENT_SECRET" | hcp configure -i $HCP_CLIENT_ID --secret-stdin
          echo "Retrieving secrets from HCP Vault Secrets"
          eval $(hcp vault-secrets env)
          echo "Secrets injected into environment"
      
      - name: Run script with Vault Secrets
        env:
          STEP1: ${{ env.Step1 }}
          STEP2: ${{ env.Step2 }}
          STEP3: ${{ env.Step3 }}
        run: |
          python app.py
