name: Use HCP Vault Secrets in GitHub Actions

on:
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
      
      - name: Install HCP CLI (Direct Download)
        run: |
          HCP_CLI_VERSION=$(curl -s https://api.releases.hashicorp.com/v1/releases/hcp-cli/latest | jq -r '.version')
          curl -LO https://releases.hashicorp.com/hcp-cli/${HCP_CLI_VERSION}/hcp-cli_${HCP_CLI_VERSION}_linux_amd64.zip
          unzip hcp-cli_${HCP_CLI_VERSION}_linux_amd64.zip
          sudo mv hcp /usr/local/bin/
          rm hcp-cli_${HCP_CLI_VERSION}_linux_amd64.zip
      
      - name: Authenticate with HCP Vault Secrets and Retrieve Secrets
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
        run: |
          echo "$HCP_CLIENT_SECRET" | hcp configure -i $HCP_CLIENT_ID --secret-stdin
          echo "Retrieving secrets from HCP Vault Secrets"
          eval $(hcp vault-secrets env)
          echo "Secrets injected into environment"
      
      - name: Run script with Vault Secrets
        env:
          STEP1: ${{ env.Step1 }}
          STEP2: ${{ env.Step2 }}
          STEP3: ${{ env.Step3 }}
        run: |
          python app.py
